/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ClienteController;
import Controller.ItemPedidoController;
import Controller.ProdutoController;
import Controller.VendasController;
import Model.ItemPedido;
import Model.Produto;
import Model.Venda;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author guilherme
 */
public class TelaPrincipal extends javax.swing.JFrame {

    private ArrayList<String[]> listaCarrinho;
    private String modoTela;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        DesabilitarFormulario();
        tblProdutos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                Produto p = ProdutoController.getProdutoById(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0).toString());
                //System.out.println(p.getDescProduto());

                lblNomeProduto.setText(p.getNomeProduto());
                txtDescricaoProduto.setText(p.getDescProduto());
            }
        });
        this.listaCarrinho = new ArrayList<>();

    }

    public void LimparFormularioCadProduto() {
        txtNomeProduto.setText("");
        txtDescProduto.setText("");
        txtPesquisaProduto.setText("");
        txtQtdProduto.setText("");
        txtVlrUnitarioProd.setText("");
    }

    private boolean ValidarFormulario() {

        boolean pass = true;

        if (this.cboCategoriaProduto.getSelectedIndex() == 0) {
            cboCategoriaProduto.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        } else {
            cboCategoriaProduto.setBorder(BorderFactory.createEmptyBorder());
        }

        if (this.txtNomeProduto.getText().equalsIgnoreCase("")) {
            txtNomeProduto.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        } else {
            txtNomeProduto.setBorder(BorderFactory.createEmptyBorder());
        }

        if (this.txtDescProduto.getText().equalsIgnoreCase("")) {
            txtDescProduto.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        } else {
            txtDescProduto.setBorder(BorderFactory.createEmptyBorder());
        }

        try {
            Integer.parseInt(this.txtQtdProduto.getText());
            txtQtdProduto.setBorder(BorderFactory.createLineBorder(Color.gray));
        } catch (NumberFormatException e) {
            txtQtdProduto.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        }

        try {
            Integer.parseInt(this.txtVlrUnitarioProd.getText());
            txtVlrUnitarioProd.setBorder(BorderFactory.createLineBorder(Color.gray));
        } catch (NumberFormatException e) {
            txtVlrUnitarioProd.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        }

        return pass;

    }

    private boolean ValidarFormularioBusca() {

        boolean pass = true;

        if (this.txtPesquisaProduto.getText().equalsIgnoreCase("")) {
            txtPesquisaProduto.setBorder(BorderFactory.createLineBorder(Color.red));
            pass = false;
        } else {
            txtPesquisaProduto.setBorder(BorderFactory.createEmptyBorder());
        }

        return pass;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtBuscaProduto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        lblNomeProduto = new javax.swing.JLabel();
        txtQuantidadeCarrinho1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        btnAdicionaCarrinho1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtDescricaoProduto = new javax.swing.JTextArea();
        jLabel21 = new javax.swing.JLabel();
        txtBuscaCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnBuscarProduto = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblCarrinho = new javax.swing.JTable();
        btnRemoveCarrinho = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnFinalizaPagamento = new javax.swing.JButton();
        cboFormadepagamento = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNomeProduto = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtQtdProduto = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescProduto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVlrUnitarioProd = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        cboCategoriaProduto = new javax.swing.JComboBox<>();
        btnNovoProduto = new javax.swing.JButton();
        btnSalvaProduto = new javax.swing.JButton();
        btnEditaProduto = new javax.swing.JButton();
        btnExcluiProduto = new javax.swing.JButton();
        txtPesquisaProduto = new javax.swing.JFormattedTextField();
        botaoOk = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCancelaCadastro = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProdutosCadastrados = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel10.setText("Codigo ou Nome do Produto: ");

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do Produto", "Nome Produto", "Categ.", "Valor Unitário R$"
            }
        ));
        jScrollPane2.setViewportView(tblProdutos);

        lblNomeProduto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNomeProduto.setText("Nome Do Produto");

        jLabel20.setText("QTD");

        btnAdicionaCarrinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/plus-16.png"))); // NOI18N
        btnAdicionaCarrinho1.setText("Adicionar");
        btnAdicionaCarrinho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionaCarrinho1ActionPerformed(evt);
            }
        });

        txtDescricaoProduto.setEditable(false);
        txtDescricaoProduto.setBackground(new java.awt.Color(209, 209, 209));
        txtDescricaoProduto.setColumns(20);
        txtDescricaoProduto.setLineWrap(true);
        txtDescricaoProduto.setRows(5);
        jScrollPane6.setViewportView(txtDescricaoProduto);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(lblNomeProduto)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 205, Short.MAX_VALUE)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQuantidadeCarrinho1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAdicionaCarrinho1)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(lblNomeProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidadeCarrinho1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(btnAdicionaCarrinho1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel21.setText("Cliente: ");

        btnBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/research.png"))); // NOI18N
        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nome Completo", "CPF", "E-Mail"
            }
        ));
        jScrollPane4.setViewportView(tblClientes);

        btnBuscarProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/research.png"))); // NOI18N
        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        btnCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/plus-16.png"))); // NOI18N
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 971, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCadastrarCliente))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btnBuscarProduto))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnCadastrarCliente))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProduto))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Carrinho"));

        tblCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo do Produto", "Nome Produto", "Qtd", "Valor Total Item R$"
            }
        ));
        jScrollPane5.setViewportView(tblCarrinho);

        btnRemoveCarrinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/delete-16.png"))); // NOI18N
        btnRemoveCarrinho.setText("Remover");
        btnRemoveCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCarrinhoActionPerformed(evt);
            }
        });

        jLabel22.setText("Valor Total R$");

        lblValor.setText("0.00");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)
                        .addGap(18, 18, 18)
                        .addComponent(btnRemoveCarrinho)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRemoveCarrinho)
                    .addComponent(jLabel22)
                    .addComponent(lblValor))
                .addGap(66, 66, 66))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Formas de pagamento"));

        btnFinalizaPagamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/approval-16.png"))); // NOI18N
        btnFinalizaPagamento.setText("Finalizar pagamento");
        btnFinalizaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizaPagamentoActionPerformed(evt);
            }
        });

        cboFormadepagamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão de Crédito", "Cartão de Debito", "Boleto" }));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(cboFormadepagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(btnFinalizaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboFormadepagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinalizaPagamento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane2.addTab("Registro de Venda", new javax.swing.ImageIcon(getClass().getResource("/View/imgs/online-shop.png")), jPanel5, ""); // NOI18N

        jLabel1.setText("Produto:");

        jLabel2.setText("Quantidade:");

        txtQtdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtdProdutoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descrição Produto:");

        jLabel4.setText("Valor Unitário R$:");

        jLabel5.setText("Selecionar Categoria:");

        cboCategoriaProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Computador", "Notebook", "Peças", "Acessórios" }));
        cboCategoriaProduto.setToolTipText("");

        btnNovoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/plus-16.png"))); // NOI18N
        btnNovoProduto.setText("Novo");
        btnNovoProduto.setMaximumSize(new java.awt.Dimension(55, 23));
        btnNovoProduto.setMinimumSize(new java.awt.Dimension(55, 23));
        btnNovoProduto.setPreferredSize(new java.awt.Dimension(62, 23));
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        btnSalvaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/save-16.png"))); // NOI18N
        btnSalvaProduto.setText("Salvar");
        btnSalvaProduto.setMaximumSize(new java.awt.Dimension(55, 23));
        btnSalvaProduto.setMinimumSize(new java.awt.Dimension(55, 23));
        btnSalvaProduto.setPreferredSize(new java.awt.Dimension(62, 23));
        btnSalvaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvaProdutoActionPerformed(evt);
            }
        });

        btnEditaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/edit-16.png"))); // NOI18N
        btnEditaProduto.setText("Editar");
        btnEditaProduto.setPreferredSize(new java.awt.Dimension(62, 23));
        btnEditaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditaProdutoActionPerformed(evt);
            }
        });

        btnExcluiProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/delete-16.png"))); // NOI18N
        btnExcluiProduto.setText("Excluir");
        btnExcluiProduto.setMaximumSize(new java.awt.Dimension(81, 25));
        btnExcluiProduto.setMinimumSize(new java.awt.Dimension(81, 25));
        btnExcluiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluiProdutoActionPerformed(evt);
            }
        });

        botaoOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/research.png"))); // NOI18N
        botaoOk.setText("Buscar");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        jLabel6.setText("Pesquisar:");

        btnCancelaCadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imgs/delete-2-16.png"))); // NOI18N
        btnCancelaCadastro.setText("Cancelar");
        btnCancelaCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelaCadastroActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Cadastrados"));

        tblProdutosCadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Cod. Produto", "Categ.", "Nome Produto", "Desc. Produto", "Qntd.", "Vlr. Unit. R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblProdutosCadastrados);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jLabel3))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDescProduto)
                                    .addComponent(txtNomeProduto))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSalvaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEditaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnExcluiProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelaCadastro)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoOk, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtVlrUnitarioProd, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(txtQtdProduto))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cboCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtQtdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtVlrUnitarioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExcluiProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalvaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelaCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNovoProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(botaoOk))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Estoque de Produtos", new javax.swing.ImageIcon(getClass().getResource("/View/imgs/package.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1033, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Relatorios", new javax.swing.ImageIcon(getClass().getResource("/View/imgs/profits.png")), jPanel10); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtQtdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQtdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtdProdutoActionPerformed

    private void btnSalvaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvaProdutoActionPerformed
        if (ValidarFormulario()) {
            if (modoTela.equals("Criar")) {
                Produto p = new Produto(
                        cboCategoriaProduto.getSelectedItem().toString(),
                        txtNomeProduto.getText(),
                        txtDescProduto.getText(),
                        Integer.parseInt(this.txtQtdProduto.getText()),
                        Float.parseFloat(txtVlrUnitarioProd.getText())
                );

                JOptionPane.showMessageDialog(this, "Produto Cadastrado com sucesso!!");
                ProdutoController.Salvar(p);
                LimparFormularioCadProduto();
            } else {
                Produto p = new Produto(
                        cboCategoriaProduto.getSelectedItem().toString(),
                        txtNomeProduto.getText(),
                        txtDescProduto.getText(),
                        Integer.parseInt(this.txtQtdProduto.getText()),
                        Float.parseFloat(txtVlrUnitarioProd.getText())
                );
                p.setcodProduto(Integer.parseInt(tblProdutosCadastrados.getValueAt(tblProdutosCadastrados.getSelectedRow(), 0).toString()));
                JOptionPane.showMessageDialog(this, "Produto Atualizado com sucesso!!");
                ProdutoController.Atualizar(p);
                LimparFormularioCadProduto();
                this.LoadSearchProduct(txtPesquisaProduto.getText(), "cadastroProduto");

            }

        } else {
            JOptionPane.showMessageDialog(this, "Preencher corretamente os campos ! ");

        }
    }//GEN-LAST:event_btnSalvaProdutoActionPerformed

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed

        //LoadTableProdutos();
        this.LoadSearchProduct(txtPesquisaProduto.getText(), "cadastroProduto");

        //this.LoadTable();
        //this.LoadSearchProduct(txtbuscaProduto.getText());
    }//GEN-LAST:event_botaoOkActionPerformed

    private void btnCancelaCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelaCadastroActionPerformed
        LimparFormularioCadProduto();
    }//GEN-LAST:event_btnCancelaCadastroActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        // TODO add your handling code here:

        this.LoadSearch(txtBuscaCliente.getText());
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        // TODO add your handling code here:
        //this.LoadTable();
        this.LoadSearchProduct(txtBuscaProduto.getText(), "cadastroVenda");
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        cadastroCliente cdCliente = new cadastroCliente();
        cdCliente.setVisible(true);
        cdCliente.setDefaultCloseOperation(cadastroCliente.DISPOSE_ON_CLOSE); // para fechar apenas a tela secundaria
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnAdicionaCarrinho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionaCarrinho1ActionPerformed
        // TODO add your handling code here:
        addCarrinho(txtQuantidadeCarrinho1.getText());
    }//GEN-LAST:event_btnAdicionaCarrinho1ActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        modoTela = "Criar";
        HabilitarFormulario();
        LimparFormulario();

    }//GEN-LAST:event_btnNovoProdutoActionPerformed


    private void btnRemoveCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCarrinhoActionPerformed
        if (tblCarrinho.getRowCount() > 0) {

            listaCarrinho.remove(tblCarrinho.getSelectedRow());
            LoadCarrinhoRemove();
        }
    }//GEN-LAST:event_btnRemoveCarrinhoActionPerformed

    private void btnFinalizaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizaPagamentoActionPerformed
        // TODO add your handling code here:
        int idCliente = 0;
        if (tblClientes.getSelectedRow() >= 0) {
            idCliente = Integer.parseInt(tblClientes.getValueAt(tblClientes.getSelectedRow(), 0).toString());
            if (listaCarrinho.size() > 0) {
                String formaPagamento = cboFormadepagamento.getSelectedItem().toString();

                Venda v = new Venda(Double.parseDouble(lblValor.getText()), formaPagamento, idCliente);
                int idVenda = VendasController.Salvar(v);
                
                for (int i = 0; i < listaCarrinho.size(); i++) {
                    ItemPedido p = new ItemPedido(v.getIdVenda(), Integer.parseInt(listaCarrinho.get(i)[0]), Integer.parseInt(listaCarrinho.get(i)[2]), Float.parseFloat(listaCarrinho.get(i)[3]));
                    ItemPedidoController.Salvar(p);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Voce deve selecionar ao menos um produto");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para a venda ser finalizada");

        }


    }//GEN-LAST:event_btnFinalizaPagamentoActionPerformed

    private void btnEditaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditaProdutoActionPerformed

        if (tblProdutosCadastrados.getRowCount() > 0) {
            if (tblProdutosCadastrados.getSelectedRow() >= 0) {
                HabilitarFormulario();
                modoTela = "Editar";

                txtNomeProduto.setText(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 2).toString());
                txtDescProduto.setText(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 3).toString());
                txtQtdProduto.setText(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 4).toString());
                txtVlrUnitarioProd.setText(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 5).toString());
                cboCategoriaProduto.setSelectedItem(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 1).toString());
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cliente para editar!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há clientes para editar!");
        }

    }//GEN-LAST:event_btnEditaProdutoActionPerformed

    private void btnExcluiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluiProdutoActionPerformed
        // TODO add your handling code here:
        if (ProdutoController.Excluir(tblProdutosCadastrados.getModel().getValueAt(tblProdutosCadastrados.getSelectedRow(), 0).toString())) {
            this.LoadSearchProduct(txtPesquisaProduto.getText(), "cadastroProduto");
        }


    }//GEN-LAST:event_btnExcluiProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    public void addCarrinho(String qtd) {

        double valor = Double.parseDouble(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 5).toString()) * Integer.parseInt(qtd);
        lblValor.setText(Double.toString(valor + Double.parseDouble(lblValor.getText())));
        this.listaCarrinho.add(new String[]{String.valueOf(tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 0).toString()), tblProdutos.getValueAt(tblProdutos.getSelectedRow(), 1).toString(), qtd, Double.toString(valor)});
        DefaultTableModel tmiTems = new DefaultTableModel();
        tmiTems.addColumn("Codigo do Produto");
        tmiTems.addColumn("Nome Produto");
        tmiTems.addColumn("Qtd");
        tmiTems.addColumn("Valor");
        for (String[] c : this.listaCarrinho) {
            tmiTems.addRow(c);
        }
        System.out.println("CLICOU");

        tblCarrinho.setModel(tmiTems);

    }

    public void LoadCarrinhoRemove() {

        DefaultTableModel tmiTems = new DefaultTableModel();
        tmiTems.addColumn("Codigo do Produto");
        tmiTems.addColumn("Nome Produto");
        tmiTems.addColumn("Qtd");
        tmiTems.addColumn("Valor");
        for (String[] c : this.listaCarrinho) {
            tmiTems.addRow(c);
        }

        double total = Double.parseDouble(lblValor.getText()) - Double.parseDouble(tblCarrinho.getValueAt(tblCarrinho.getSelectedRow(), 3).toString());
        lblValor.setText(Double.toString(total));
        tblCarrinho.setModel(tmiTems);

    }

    public void LimparFormulario() {
        txtNomeProduto.setText("");
        txtDescProduto.setText("");
        txtQtdProduto.setText("");
        txtVlrUnitarioProd.setText("");
    }

    public void DesabilitarFormulario() {
        txtNomeProduto.setEditable(false);
        txtDescProduto.setEditable(false);
        txtQtdProduto.setEditable(false);
        txtVlrUnitarioProd.setEditable(false);
        btnSalvaProduto.setEnabled(false);
        btnCancelaCadastro.setEnabled(false);
        btnEditaProduto.setEnabled(false);
        btnExcluiProduto.setEnabled(false);
        cboCategoriaProduto.setEnabled(false);
    }

    public void HabilitarFormulario() {
        txtNomeProduto.setEditable(true);
        txtDescProduto.setEditable(true);
        txtQtdProduto.setEditable(true);
        txtVlrUnitarioProd.setEditable(true);
        btnSalvaProduto.setEnabled(true);
        btnCancelaCadastro.setEnabled(true);
        btnEditaProduto.setEnabled(true);
        btnExcluiProduto.setEnabled(true);
        cboCategoriaProduto.setEnabled(true);
    }

    public void LoadSearch(String busca) {
        System.out.println("TESTE LOAD");
        ArrayList<String[]> linhasClientes = ClienteController.buscaCliente(busca);

        DefaultTableModel tmClientes = new DefaultTableModel();

        tmClientes.addColumn("ID Cliente");
        tmClientes.addColumn("Nome Completo");
        tmClientes.addColumn("CPF");
        tmClientes.addColumn("E-Mail");

        for (String[] c : linhasClientes) {
            tmClientes.addRow(c);
        }

        tblClientes.setModel(tmClientes);
    }

    public void LoadSearchProduct(String busca, String context) {

        ArrayList<String[]> linhasProdutos = ProdutoController.getProdutos(busca);

        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("Cod. Produto");
        tmProdutos.addColumn("Categ.");
        tmProdutos.addColumn("Nome Produto");
        tmProdutos.addColumn("Desc. Produto");
        tmProdutos.addColumn("Qntd.");
        tmProdutos.addColumn("Vlr. Unit. R$");

        for (String[] c : linhasProdutos) {
            tmProdutos.addRow(c);
        }
        if (context.equals("cadastroVenda")) {
            tblProdutos.setModel(tmProdutos);
        } else if (context.equals("cadastroProduto")) {
            tblProdutosCadastrados.setModel(tmProdutos);
        }
    }

    public void LoadTableProdutos() {

        ArrayList<String[]> linhasProdutos = ProdutoController.getProdutos(txtBuscaProduto.getText());

        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("Código Produto");
        tmProdutos.addColumn("Nome ");
        tmProdutos.addColumn("Categoria");
        tmProdutos.addColumn("Valor Unitario");
        for (String[] c : linhasProdutos) {
            tmProdutos.addRow(c);
        }

        tblProdutosCadastrados.setModel(tmProdutos);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoOk;
    private javax.swing.JButton btnAdicionaCarrinho1;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnCancelaCadastro;
    private javax.swing.JButton btnEditaProduto;
    private javax.swing.JButton btnExcluiProduto;
    private javax.swing.JButton btnFinalizaPagamento;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnRemoveCarrinho;
    private javax.swing.JButton btnSalvaProduto;
    private javax.swing.JComboBox<String> cboCategoriaProduto;
    private javax.swing.JComboBox<String> cboFormadepagamento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTable tblCarrinho;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTable tblProdutosCadastrados;
    private javax.swing.JTextField txtBuscaCliente;
    private javax.swing.JTextField txtBuscaProduto;
    private javax.swing.JFormattedTextField txtDescProduto;
    private javax.swing.JTextArea txtDescricaoProduto;
    private javax.swing.JFormattedTextField txtNomeProduto;
    private javax.swing.JFormattedTextField txtPesquisaProduto;
    private javax.swing.JFormattedTextField txtQtdProduto;
    private javax.swing.JTextField txtQuantidadeCarrinho1;
    private javax.swing.JFormattedTextField txtVlrUnitarioProd;
    // End of variables declaration//GEN-END:variables
}
